#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-t-digest
Version  : 3.0
Release  : 1
URL      : https://github.com/tdunning/t-digest/archive/t-digest-3.0.tar.gz
Source0  : https://github.com/tdunning/t-digest/archive/t-digest-3.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/tdunning/t-digest/3.0/t-digest-3.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/tdunning/t-digest/3.0/t-digest-3.0.pom
Source3  : https://repo.maven.apache.org/maven2/com/tdunning/t-digest/3.2/t-digest-3.2.jar
Source4  : https://repo.maven.apache.org/maven2/com/tdunning/t-digest/3.2/t-digest-3.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-t-digest-data = %{version}-%{release}
Requires: mvn-t-digest-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
t-digest
========
A new data structure for accurate on-line accumulation of rank-based statistics such as quantiles
and trimmed means.  The t-digest algorithm is also very parallel friendly making it useful in
map-reduce and parallel streaming applications.

%package data
Summary: data components for the mvn-t-digest package.
Group: Data

%description data
data components for the mvn-t-digest package.


%package license
Summary: license components for the mvn-t-digest package.
Group: Default

%description license
license components for the mvn-t-digest package.


%prep
%setup -q -n t-digest-t-digest-3.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-t-digest
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-t-digest/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.0/t-digest-3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.0/t-digest-3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.2/t-digest-3.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/tdunning/t-digest/3.2/t-digest-3.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/tdunning/t-digest/3.0/t-digest-3.0.jar
/usr/share/java/.m2/repository/com/tdunning/t-digest/3.0/t-digest-3.0.pom
/usr/share/java/.m2/repository/com/tdunning/t-digest/3.2/t-digest-3.2.jar
/usr/share/java/.m2/repository/com/tdunning/t-digest/3.2/t-digest-3.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-t-digest/LICENSE
